use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :mems, MemsWeb.Endpoint,
  url: [host: {:system, "MLR_HOST"}],
  http: [
    :inet6,
    port: {:system, "MLR_HTTP_PORT"},
    compress: true,
  ],
  cache_static_manifest: "priv/static/cache_manifest.json"
  

# To add SSL - try this
  #https: [
    #port: {:system, "MLR_HTTPS_PORT"},
    #otp_app: :mems,
    #cipher_suite: :compatible,
    #keyfile: {:system, "MLR_SSL_KEYFILE"},
    ##keyfile: "priv/cert/selfsigned_key.pem",
    #certfile: {:system, "MLR_SSL_CERTFILE"},
    ##certfile: "priv/cert/selfsigned.pem",
    #transport_options: [socket_opts: [:inet6]],
    #force_ssl: [hsts: true]
    #]

# Do not print debug messages in production
config :logger, level: :info
